#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = 'Selbi Nuryyeva'
__date__ = 'September 21, 2020'

# A python script that takes the XTB CREST crest_conformers.xyz file and
# generates the gjf input files for Gaussian software with each conformer in a
# separate gjf file

# Please make sure the folder has the "crest_conformers.xyz" generated by XTB CREST

# To execute it: "python3 xyz-to-gjf.py"

# Number of cores, memory, method, basis set, charge and multiplicity can be
# modified in lines 38-44.

import sys
import os

cfile = open('crest_conformers.xyz')

# a integer that just counts the number of conformer being processed
# and is used for re-labeling of output gjf files
a = 0
output = 'conf' + str(a) + '.gjf'
coutput = open(output, 'w')

for cline in cfile:
	if cline[1].isalpha() == True:
		coutput.write(cline)
	if cline[2].isdigit() == True:
		coutput.write("\n")
		coutput.close()
		a = a + 1
		output = 'conf' + str(a) + '.gjf'
		coutput = open(output, 'w')
		coutput.write("%mem=3GB\n")
		coutput.write("%nproc=2\n")
		coutput.write("# opt=calcfc freq=noraman wb97xd/6-31G(d)\n")
		coutput.write("\n")
		coutput.write(output[:-4] + "\n")
		coutput.write("\n")
		coutput.write("0 1\n")

# conf0.gjf is an empty file that is generated as a by-product. Needs to be deleted afterwards.
os.remove("conf0.gjf")

# since coutput.write(cline) does not leave the cursor on new line, we print new line twice: 
# one for moving cursor to new line and one for an actual empty line
coutput.write("\n")
coutput.write("\n")

coutput.close()
